import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./../styles/globals.css";
import "./../styles/search-menu.css";
import "./../styles/bloglist.css";
import "./../styles/label.css";
import "./../styles/modal.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
