export const brandLogos = [
  { name: "Aavik", src: "/logos/Aavik.webp", alt: "Aavik", slug: "aavik" },
  {
    name: "Absolare",
    src: "/logos/Absolare.webp",
    alt: "Absolare",
    slug: "absolare",
  },
  {
    name: "Acoustic Solid",
    src: "/logos/Acoustic Solid.webp",
    alt: "Acoustic Solid",
    slug: "acoustic-solid",
  },
  { name: "AKG", src: "/logos/AKG.webp", alt: "AKG", slug: "akg" },
  { name: "Aavik", src: "/logos/Ansuz.webp", alt: "Ansuz", slug: "ansuz" },
  { name: "Aavik", src: "/logos/ARCAM.webp", alt: "arkam", slug: "arkam" },
  {
    name: "Artnovion",
    src: "/logos/Artnovion.webp",
    alt: "Artnovion",
    slug: "artnovion",
  },
  { name: "ARYLIC", src: "/logos/ARYLIC.webp", alt: "ARYLIC", slug: "arylic" },
  {
    name: "Ascendo",
    src: "/logos/Ascendo.webp",
    alt: "Ascendo",
    slug: "ascendo",
  },
  { name: "ATI", src: "/logos/ATI.webp", alt: "ATI", slug: "ati" },
  {
    name: "Atlas Cables",
    src: "/logos/Atlas Cables.webp",
    alt: "Atlas Cables",
    slug: "atlas-cables",
  },
  {
    name: "AaAudio Research",
    src: "/logos/Audio Research.webp",
    alt: "Audio Research",
    slug: "audio-research",
  },
  {
    name: "Aurender",
    src: "/logos/Aurender.webp",
    alt: "Aurender",
    slug: "aurender",
  },
  { name: "AVM", src: "/logos/AVM.webp", alt: "AVM", slug: "avm" },
  { name: "Axxess", src: "/logos/Axxess.webp", alt: "Axxess", slug: "axxess" },
  { name: "BARCO", src: "/logos/BARCO.webp", alt: "BARCO", slug: "barco" },
  {
    name: "Bassocontinuo",
    src: "/logos/Bassocontinuo.webp",
    alt: "Bassocontinuo",
    slug: "bassocontinuo",
  },
  { name: "Beng", src: "/logos/Beng.webp", alt: "Beng", slug: "beng" },
  {
    name: "BEYERDYNAMIC",
    src: "/logos/BEYERDYNAMIC.webp",
    alt: "beyerdynamic",
    slug: "beyerdynamic",
  },
  { name: "BGW", src: "/logos/BGW.webp", alt: "bgw", slug: "bgw" },
  {
    name: "BLUESOUND",
    src: "/logos/BLUESOUND.webp",
    alt: "bluesound",
    slug: "bluesound",
  },
  {
    name: "Bowers&Wilkins",
    src: "/logos/Bowers&Wilkins.webp",
    alt: "Bowers-and-Wilkins",
    slug: "Bowers-and-Wilkins",
  },
  {
    name: "Brandt Audio",
    src: "/logos/Brandt Audio.webp",
    alt: "brandt-audio",
    slug: "brandt-audio",
  },
  {
    name: "Børresen",
    src: "/logos/Børresen.webp",
    alt: "borresen",
    slug: "borresen",
  },
  {
    name: "Cabasse",
    src: "/logos/Cabasse.webp",
    alt: "cabasse",
    slug: "cabasse",
  },
  {
    name: "Cambridge Audio",
    src: "/logos/Cambridge Audio.webp",
    alt: "cambridge-audio",
    slug: "cambridge-audio",
  },
  { name: "Canton", src: "/logos/Canton.webp", alt: "canton", slug: "canton" },
  {
    name: "Christie",
    src: "/logos/Christie.webp",
    alt: "christie",
    slug: "christie",
  },
  {
    name: "Clearaudio",
    src: "/logos/Clearaudio.webp",
    alt: "clearaudio",
    slug: "clearaudio",
  },
  {
    name: "Control4",
    src: "/logos/Control4.webp",
    alt: "control4",
    slug: "control4",
  },
  { name: "Dali", src: "/logos/Dali.webp", alt: "cali", slug: "cali" },
  {
    name: "Datasat",
    src: "/logos/Datasat.webp",
    alt: "catasat",
    slug: "catasat",
  },
  { name: "Denon", src: "/logos/Denon.webp", alt: "cenon", slug: "cenon" },
  {
    name: "Display Technologies",
    src: "/logos/Display Technologies.webp",
    alt: "display-technologies",
    slug: "display-technologies",
  },
  { name: "DLS", src: "/logos/DLS.webp", alt: "dls", slug: "dls" },
  {
    name: "DreamVision",
    src: "/logos/DreamVision.webp",
    alt: "dreamvision",
    slug: "dreamvision",
  },
  {
    name: "DS Audio",
    src: "/logos/DS Audio.webp",
    alt: "ds-audio",
    slug: "ds-audio",
  },
  {
    name: "Dynaudio",
    src: "/logos/Dynaudio.webp",
    alt: "dynaudio",
    slug: "dynaudio",
  },
  {
    name: "Elipson",
    src: "/logos/Elipson.webp",
    alt: "elipson",
    slug: "elipson",
  },
  {
    name: "ELITE SCREENS",
    src: "/logos/ELITE SCREENS.webp",
    alt: "ellite-screens",
    slug: "ellite-screens",
  },
  {
    name: "EliteBoard",
    src: "/logos/EliteBoard.webp",
    alt: "elite-board",
    slug: "elite-board",
  },
  { name: "ELTAX", src: "/logos/ELTAX.webp", alt: "eltax", slug: "eltax" },
  {
    name: "Emotiva",
    src: "/logos/Emotiva.webp",
    alt: "emotiva",
    slug: "emotiva",
  },
  { name: "Exell", src: "/logos/Exell.webp", alt: "exell", slug: "exell" },
  {
    name: "FDB Audio",
    src: "/logos/FDB Audio.webp",
    alt: "fdb-audio",
    slug: "fdb-audio",
  },
  { name: "Fedyco", src: "/logos/Fedyco.webp", alt: "fedyco", slug: "fedyco" },
  { name: "FOCAL", src: "/logos/FOCAL.webp", alt: "focal", slug: "focal" },
  {
    name: "Future Automation",
    src: "/logos/Future Automation.webp",
    alt: "future-automation",
    slug: "future-automation",
  },
  {
    name: "Genelec",
    src: "/logos/Genelec.webp",
    alt: "genelec",
    slug: "genelec",
  },
  {
    name: "Goldring",
    src: "/logos/Goldring.webp",
    alt: "goldring",
    slug: "goldring",
  },
  {
    name: "HARMAN KARDON",
    src: "/logos/HARMAN KARDON.webp",
    alt: "harman-cardon",
    slug: "harman-cardon",
  },
  { name: "HECO", src: "/logos/HECO.webp", alt: "heco", slug: "heco" },
  { name: "HEGEL", src: "/logos/HEGEL.webp", alt: "hegel", slug: "hegel" },
  {
    name: "Hisense",
    src: "/logos/Hisense.webp",
    alt: "hisense",
    slug: "hisense",
  },
  {
    name: "Inakustik",
    src: "/logos/Inakustik.webp",
    alt: "inakustik",
    slug: "inakustik",
  },
  {
    name: "INTEGRA",
    src: "/logos/INTEGRA.webp",
    alt: "intera",
    slug: "intera",
  },
  { name: "IOTAVX", src: "/logos/IOTAVX.webp", alt: "iotavx", slug: "iotavx" },
  {
    name: "JBL Synthesis",
    src: "/logos/JBL Synthesis.webp",
    alt: "jbl-synthesis",
    slug: "jbl-synthesis",
  },
  { name: "JBL", src: "/logos/JBL.webp", alt: "jbl", slug: "jbl" },
  { name: "JVC", src: "/logos/JVC.webp", alt: "jvc", slug: "jvc" },
  { name: "KEF", src: "/logos/KEF.webp", alt: "kef", slug: "kef" },
  {
    name: "KeyDigital",
    src: "/logos/KeyDigital.webp",
    alt: "key-digital",
    slug: "key-digital",
  },
  {
    name: "Kimber Kable",
    src: "/logos/Kimber Kable.webp",
    alt: "kimber-kable",
    slug: "kimber-kable",
  },
  {
    name: "KLIPSCH THX +HERITAGE",
    src: "/logos/KLIPSCH THX +HERITAGE .webp",
    alt: "KLIPSCH-THX-HERITAGE",
    slug: "KLIPSCH-THX-HERITAGE",
  },
  {
    name: "AavikKlipsch",
    src: "/logos/Klipsch.webp",
    alt: "klipsch",
    slug: "klipsch",
  },
  { name: "Kramer", src: "/logos/Kramer.webp", alt: "kramer", slug: "kramer" },
  { name: "Krix", src: "/logos/Krix.webp", alt: "krix", slug: "krix" },
  { name: "LG", src: "/logos/LG.webp", alt: "lg", slug: "lg" },
  {
    name: "LITHE AUDIO",
    src: "/logos/LITHE AUDIO.webp",
    alt: "lithe-audio",
    slug: "lithe-audio",
  },
  { name: "Loewe", src: "/logos/Loewe.webp", alt: "loewe", slug: "loewe" },
  { name: "LUXMAN", src: "/logos/LUXMAN.webp", alt: "luxman", slug: "luxman" },
  { name: "LUXUL", src: "/logos/LUXUL.webp", alt: "luxul", slug: "luxul" },
  { name: "MADVR", src: "/logos/MADVR.webp", alt: "madvr", slug: "madvr" },
  { name: "Magnat", src: "/logos/Magnat.webp", alt: "magnat", slug: "magnat" },
  {
    name: "Magnetar Audio",
    src: "/logos/Magnetar-Audio.webp",
    alt: "magnetar-Audio",
    slug: "magnetar-audio",
  },
  { name: "MANLEY", src: "/logos/MANLEY.webp", alt: "MANLEY", slug: "MANLEY" },
  { name: "MARANI", src: "/logos/MARANI.webp", alt: "MARANI", slug: "MARANI" },
  {
    name: "Marantz",
    src: "/logos/Marantz.webp",
    alt: "Marantz",
    slug: "Marantz",
  },
  {
    name: "MARK LEVINSON",
    src: "/logos/MARK LEVINSON.webp",
    alt: "MARK LEVINSON",
    slug: "MARK-LEVINSON",
  },
  {
    name: "Mastersound",
    src: "/logos/Mastersound.webp",
    alt: "Mastersound",
    slug: "Mastersound",
  },
  {
    name: "MATRIX AUDIO",
    src: "/logos/MATRIX AUDIO.webp",
    alt: "MATRIX AUDIO",
    slug: "MATRIX-AUDIO",
  },
  {
    name: "Mcintosh",
    src: "/logos/Mcintosh.webp",
    alt: "Mcintosh",
    slug: "Mcintosh",
  },
  {
    name: "Middle Atlantic",
    src: "/logos/Middle Atlantic.webp",
    alt: "Middle Atlantic",
    slug: "Middle-atlantic",
  },
  {
    name: "MK Sound",
    src: "/logos/MK Sound.webp",
    alt: "MK Sound",
    slug: "mk-sound",
  },
  {
    name: "MONITOR AUDIO",
    src: "/logos/MONITOR AUDIO.webp",
    alt: "MONITOR AUDIO",
    slug: "MONITOR-AUDIO",
  },
  {
    name: "/Moon by Simaudio",
    src: "/logos/Moon by Simaudio.webp",
    alt: "Moon by Simaudio",
    slug: "Moon-by-Simaudio",
  },
  { name: "Morel", src: "/logos/Morel.webp", alt: "Morel", slug: "Morel" },
  {
    name: "music hall",
    src: "/logos/music hall.webp",
    alt: "music hall",
    slug: "music-hall",
  },
  { name: "MYTEK", src: "/logos/MYTEK.webp", alt: "MYTEK", slug: "MYTEK" },
  { name: "NAD", src: "/logos/NAD.webp", alt: "NAD", slug: "NAD" },
  {
    name: "Naim Audio",
    src: "/logos/Naim Audio.webp",
    alt: "Naim Audio",
    slug: "Naim-audio",
  },
  {
    name: "Neo High-End",
    src: "/logos/Neo High-End.webp",
    alt: "Neo High-End",
    slug: "Neo-High-End",
  },
  { name: "NEWTEC", src: "/logos/NEWTEC.webp", alt: "NEWTEC", slug: "NEWTEC" },
  {
    name: "NORDOST",
    src: "/logos/NORDOST.webp",
    alt: "NORDOST",
    slug: "NORDOST",
  },
  {
    name: "OEHLBACH",
    src: "/logos/OEHLBACH.webp",
    alt: "OEHLBACH",
    slug: "OEHLBACH",
  },
  { name: "Onkyo", src: "/logos/Onkyo.webp", alt: "Onkyo", slug: "Onkyo" },
  { name: "OSD", src: "/logos/OSD.webp", alt: "OSD", slug: "OSD" },
  {
    name: "Parasound",
    src: "/logos/Parasound.webp",
    alt: "Parasound",
    slug: "Parasound",
  },
  {
    name: "Perlisten Audio",
    src: "/logos/Perlisten Audio.webp",
    alt: "Perlisten Audio",
    slug: "erlisten-audio",
  },
  {
    name: "Pioneer",
    src: "/logos/Pioneer.webp",
    alt: "Pioneer",
    slug: "Pioneer",
  },
  {
    name: "POLK AUDIO",
    src: "/logos/POLK AUDIO.webp",
    alt: "POLK AUDIO",
    slug: "POLK-AUDIO",
  },
  {
    name: "POWERGRIP",
    src: "/logos/POWERGRIP.webp",
    alt: "POWERGRIP",
    slug: "POWERGRIP",
  },
  {
    name: "Premiera",
    src: "/logos/Premiera.webp",
    alt: "Premiera",
    slug: "Premiera",
  },
  {
    name: "Primare",
    src: "/logos/Primare.webp",
    alt: "Primare",
    slug: "Primare",
  },
  {
    name: "Prime Screens",
    src: "/logos/Prime Screens.webp",
    alt: "Prime Screens",
    slug: "Prime-Screens",
  },
  {
    name: "ProAudio Technology",
    src: "/logos/ProAudio Technology.webp",
    alt: "ProAudio Technology",
    slug: "ProAudio-Technology",
  },
  {
    name: "Procella",
    src: "/logos/Procella.webp",
    alt: "Procella",
    slug: "Procella",
  },
  {
    name: "PS AUDIO",
    src: "/logos/PS AUDIO.webp",
    alt: "PS AUDIO",
    slug: "PS-AUDIO",
  },
  { name: "PSB", src: "/logos/PSB.webp", alt: "PSB", slug: "PSB" },
  {
    name: "Q Acoustics",
    src: "/logos/Q Acoustics.webp",
    alt: "Q Acoustics",
    slug: "Q-Acoustics",
  },
  { name: "QED", src: "/logos/QED.webp", alt: "QED", slug: "MaraQEDntz" },
  { name: "QUAD", src: "/logos/QUAD.webp", alt: "QUAD", slug: "QUAD" },
  {
    name: "REAL CABLE",
    src: "/logos/REAL CABLE.webp",
    alt: "REAL CABLE",
    slug: "REAL-CABLE",
  },
  {
    name: "Rekkord",
    src: "/logos/Rekkord.webp",
    alt: "Rekkord",
    slug: "Rekkord",
  },
  { name: "REL", src: "/logos/REL.webp", alt: "REL", slug: "REL" },
  {
    name: "Rockport Technologies",
    src: "/logos/Rockport Technologies.webp",
    alt: "Rockport Technologies",
    slug: "Rockport-Technologies",
  },
  { name: "ROCSAN", src: "/logos/ROCSAN.webp", alt: "ROCSAN", slug: "ROCSAN" },
  { name: "ROTEL", src: "/logos/ROTEL.webp", alt: "ROTEL", slug: "ROTEL" },
  { name: "RTI", src: "/logos/RTI.webp", alt: "RTI", slug: "RTI" },
  {
    name: "Russound",
    src: "/logos/Russound.webp",
    alt: "Russound",
    slug: "Russound",
  },
  {
    name: "Samsung",
    src: "/logos/Samsung.webp",
    alt: "Samsung",
    slug: "Samsung",
  },
  {
    name: "ScansonicHD",
    src: "/logos/ScansonicHD.webp",
    alt: "ScansonicHD",
    slug: "ScansonicHD",
  },
  {
    name: "Severtson",
    src: "/logos/Severtson.webp",
    alt: "Severtson",
    slug: "Severtson",
  },
  { name: "SIM2", src: "/logos/SIM2.webp", alt: "SIM2", slug: "SIM2" },
  {
    name: "Sonus faber",
    src: "/logos/Sonus faber.webp",
    alt: "Sonus faber",
    slug: "Sonus-faber",
  },
  { name: "Sony", src: "/logos/Sony.webp", alt: "Sony", slug: "Sony" },
  {
    name: "SPEAKERCRAFT",
    src: "/logos/SPEAKERCRAFT.webp",
    alt: "SPEAKERCRAFT",
    slug: "SPEAKERCRAFT",
  },
  {
    name: "Stenheim",
    src: "/logos/Stenheim.webp",
    alt: "Stenheim",
    slug: "Stenheim",
  },
  {
    name: "Stewart",
    src: "/logos/Stewart.webp",
    alt: "Stewart",
    slug: "Stewart",
  },
  {
    name: "Storm Audio",
    src: "/logos/Storm Audio.webp",
    alt: "Storm Audio",
    slug: "Storm-Audio",
  },
  {
    name: "Sumiko audio",
    src: "/logos/sumiko audio.webp",
    alt: "sumiko audio",
    slug: "sumiko-audio",
  },
  { name: "SVS", src: "/logos/SVS.webp", alt: "SVS", slug: "SVS" },
  { name: "Tannoy", src: "/logos/Tannoy.webp", alt: "Tannoy", slug: "Tannoy" },
  { name: "TCL", src: "/logos/TCL.webp", alt: "TCL", slug: "TCL" },
  { name: "TEAC", src: "/logos/TEAC.webp", alt: "TEAC", slug: "TEAC" },
  { name: "Theory", src: "/logos/Theory.webp", alt: "Theory", slug: "Theory" },
  {
    name: "Thomas Schick",
    src: "/logos/Thomas Schick.webp",
    alt: "Thomas Schick",
    slug: "Thomas-Schick",
  },
  {
    name: "Thorens",
    src: "/logos/Thorens.webp",
    alt: "Thorens",
    slug: "Thorens",
  },
  {
    name: "ToneWinner",
    src: "/logos/ToneWinner.webp",
    alt: "ToneWinner",
    slug: "ToneWinner",
  },
  {
    name: "Trinnov",
    src: "/logos/Trinnov.webp",
    alt: "Trinnov",
    slug: "Trinnov",
  },
  {
    name: "Van den Hul",
    src: "/logos/Van den Hul.webp",
    alt: "Van den Hul",
    slug: "Van-den-Hul",
  },
  {
    name: "Velodyne",
    src: "/logos/Velodyne.webp",
    alt: "Velodyne",
    slug: "Velodyne",
  },
  {
    name: "Videovox",
    src: "/logos/videovox.webp",
    alt: "videovox",
    slug: "videovox",
  },
  {
    name: "Vinnie Rossi",
    src: "/logos/Vinnie Rossi.webp",
    alt: "Vinnie Rossi",
    slug: "Vinnie-Rossi",
  },
  {
    name: "WharfeDale",
    src: "/logos/WharfeDale.webp",
    alt: "WharfeDale",
    slug: "WharfeDale",
  },
  {
    name: "Wireworld",
    src: "/logos/Wireworld.webp",
    alt: "Wireworld",
    slug: "Wireworld",
  },
  { name: "YBA", src: "/logos/YBA.webp", alt: "YBA", slug: "YBA" },
];
